<a href="https://colab.research.google.com/github/Ar-Anik/Machine_Learning/blob/main/nditer()_Function.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy

a = numpy.arange(1, 13).reshape(3, 4)

a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [2]:
# Print Array Each Element By flatten() function

for cell in a.flatten() : 
  print(cell)

1
2
3
4
5
6
7
8
9
10
11
12


In [3]:
# https://numpy.org/doc/stable/reference/generated/numpy.nditer.html
# nditer() function

arr = numpy.arange(1, 21).reshape(4, 5)

arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [6]:
for i in numpy.nditer(arr, order='C') :
  print(i)

1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20


In [7]:
for i in numpy.nditer(arr, order='F') :
  print(i)

1
6
11
16
2
7
12
17
3
8
13
18
4
9
14
19
5
10
15
20


In [9]:
# Array

arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [8]:
# Column Print

for i in numpy.nditer(arr, order='F', flags = ['external_loop']) :
  print(i)

[ 1  6 11 16]
[ 2  7 12 17]
[ 3  8 13 18]
[ 4  9 14 19]
[ 5 10 15 20]


In [11]:
# square of each element of the array

for i in numpy.nditer(arr, op_flags=['readwrite']) :
  i[...] = i*i

arr

array([[  1,   4,   9,  16,  25],
       [ 36,  49,  64,  81, 100],
       [121, 144, 169, 196, 225],
       [256, 289, 324, 361, 400]])

In [15]:
# iterate two array

a = numpy.arange(1, 13).reshape(3, 4)

b = numpy.arange(0, 12, 3).reshape(1, 4)

In [16]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [17]:
b

array([[0, 3, 6, 9]])

In [18]:
for i, j in numpy.nditer([a, b]) :
  print(i, j)

1 0
2 3
3 6
4 9
5 0
6 3
7 6
8 9
9 0
10 3
11 6
12 9
