<a href="https://colab.research.google.com/github/Ar-Anik/Machine_Learning/blob/main/numpy_argsort()_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# numpy.argsort(arr, axis=-1, kind=’quicksort’, order=None)

import numpy

arr = numpy.array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

arr

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [ ]:
output = numpy.argsort(arr)

output       # index number

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [ ]:
# each index number

arr[output]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
a = numpy.array([2, 0, 1, 5, 4, 1, 9])

a

array([2, 0, 1, 5, 4, 1, 9])

In [ ]:
out = numpy.argsort(a)

out

array([1, 2, 5, 0, 4, 3, 6])

In [ ]:
a[out]

array([0, 1, 1, 2, 4, 5, 9])

In [ ]:
# for 2D array

arr = numpy.array([[2, 0, 1], [5, 4, 3]])

arr

array([[2, 0, 1],
       [5, 4, 3]])

In [ ]:
output = numpy.argsort(arr, axis=1)

output

array([[1, 2, 0],
       [2, 1, 0]])

In [ ]:
numpy.take_along_axis(arr, output, axis=1) 

array([[0, 1, 2],
       [3, 4, 5]])

In [ ]:
arr = numpy.array([[2, 0, 1], [5, 4, 3], [8, 6, 7]])

arr

array([[2, 0, 1],
       [5, 4, 3],
       [8, 6, 7]])

In [ ]:
output = numpy.argsort(arr, axis=1)

output

array([[1, 2, 0],
       [2, 1, 0],
       [1, 2, 0]])

In [ ]:
numpy.take_along_axis(arr, output, axis=1)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])