<a href="https://colab.research.google.com/github/Ar-Anik/Machine_Learning/blob/main/Numpy_Array_Operation_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy

# 1 Dimensional Array
a = numpy.array([1, 2, 3, 4, 5, 6])

a

array([1, 2, 3, 4, 5, 6])

In [ ]:
print(a)

[1 2 3 4 5 6]


In [ ]:
# 2 Dimensional Array

b = numpy.array([[1, 2, 3],
                 [4, 5, 6],
                 [7, 8, 9]])

b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
print(b)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
# a array Dimension 

print(a.ndim)

1


In [ ]:
# b array Dimension

print(b.ndim)

2


In [ ]:
# a Array Element Size

a.itemsize

8

In [ ]:
# b Array Element Size

b.itemsize

8

In [ ]:
# a Array Data Type

a.dtype

dtype('int64')

In [ ]:
# b Array Data Type

b.dtype

dtype('int64')

In [ ]:
# Array Data Type Change by "dtype" keyword

c = numpy.array([1, 2, 3, 4, 5], dtype = numpy.float64)   #convert integer to float

c

array([1., 2., 3., 4., 5.])

In [ ]:
# c Array Data Type

c.dtype

dtype('float64')

In [ ]:
d = numpy.array([[1, 2, 3, 4], [5, 6, 7, 8]], dtype = numpy.float64)    # conver interger to float

d

array([[1., 2., 3., 4.],
       [5., 6., 7., 8.]])

In [ ]:
# convert integer to complex number

a = numpy.array([1, 2, 3], dtype=complex)

print(a)

[1.+0.j 2.+0.j 3.+0.j]


In [ ]:
b = numpy.array([[1, 2], [3, 4], [5, 6]], dtype = complex)

print(b)

[[1.+0.j 2.+0.j]
 [3.+0.j 4.+0.j]
 [5.+0.j 6.+0.j]]


In [ ]:
print("Data Type of Array a : ", a.dtype, '\n\n', "Data Type of Array b", b.dtype)

Data Type of Array a :  complex128 

 Data Type of Array b complex128


In [ ]:
# Size of Array

a = numpy.array([[1, 2],
                 [3, 4],
                 [5, 6] 
                ])

a.size

6

In [ ]:
# Array Shape Means row and column

a.shape

(3, 2)

In [4]:
# Declare a array and fill it all element by zero

x = numpy.zeros((4, 4))

print(x)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [5]:
# Declare a array and fill it all element by one

y = numpy.ones((5, 4))

print(y)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [6]:
# arange() function work like range() function

x = numpy.arange(10)

print(x)

[0 1 2 3 4 5 6 7 8 9]


In [7]:
a = numpy.arange(1, 10)

print(a)

[1 2 3 4 5 6 7 8 9]


In [10]:
y = numpy.arange(2, 21, 2)

print(y)

[ 2  4  6  8 10 12 14 16 18 20]


In [13]:
# linspace() function generate number between start and end number

arr = numpy.linspace(1, 2, 10)

print(arr)

[1.         1.11111111 1.22222222 1.33333333 1.44444444 1.55555556
 1.66666667 1.77777778 1.88888889 2.        ]


In [14]:
n = numpy.linspace(1, 2, 20)

print(n)

[1.         1.05263158 1.10526316 1.15789474 1.21052632 1.26315789
 1.31578947 1.36842105 1.42105263 1.47368421 1.52631579 1.57894737
 1.63157895 1.68421053 1.73684211 1.78947368 1.84210526 1.89473684
 1.94736842 2.        ]


In [15]:
# reshape() function set the exist array new dimension

a = numpy.array([[1, 2],
                 [3, 4],
                 [5, 6],
                 [7, 8]
                 ])
print("Array Row and Column : ", a.shape)

Array Row and Column :  (4, 2)


In [16]:
a = a.reshape(2, 4)

print(a)

[[1 2 3 4]
 [5 6 7 8]]


In [17]:
print("Array Row and Column after reshape : ", a.shape)

Array Row and Column after reshape :  (2, 4)


In [18]:
# N Dimension to 1 Dimension By ravel() function

arr = numpy.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]
                   ])

print(arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [21]:
new_array = arr.ravel()

print(new_array)

[1 2 3 4 5 6 7 8 9]


In [25]:
# min() function found minimum value of a array

a = numpy.array([[100, 2, 3],
                 [4, -5, 6],
                 [7, 8, 9]
                 ])

a.min()

-5

In [26]:
# max() function found minimum value of a array

a.max()

100

In [27]:
# sum() function add all value of a array
# sum(axis = 0) add each column
# sum(axis = 1) add each row

arr = numpy.array([
                   [1, 2, 3, 4],
                   [5, 6, 7, 8]
                  ])
print(arr)

[[1 2 3 4]
 [5 6 7 8]]


In [29]:
print("Sum of all element : ", arr.sum())

Sum of all element :  36


In [31]:
print("Sum of each column : ", arr.sum(axis = 0))

Sum of each column :  [ 6  8 10 12]


In [33]:
print("Sum of each row : ", arr.sum(axis = 1))

Sum of each row :  [10 26]


In [34]:
# square root all array element by numpy.sqrt(Array Name)

arr = numpy.sqrt(arr)

print(arr)

[[1.         1.41421356 1.73205081 2.        ]
 [2.23606798 2.44948974 2.64575131 2.82842712]]


In [37]:
# Standard Deviation of array count by numpy.std(Array Name)

a = numpy.array([10, 20, 30, 40, 50, 60])

std = numpy.std(a)

print("Standard Deviation : ", std)

Standard Deviation :  17.07825127659933


In [39]:
# 2 Dimensional arrays add, sub, multiplication and division
a = numpy.array([[1, 2],
                 [3, 4]])
b = numpy.array([[5, 6],
                 [7, 8]])

In [42]:
# Summation two array

print(a+b)

[[ 6  8]
 [10 12]]


In [43]:
# Subtraction of two array 

print(a-b)

[[-4 -4]
 [-4 -4]]


In [44]:
# Multiplication of two array

print(a*b)

[[ 5 12]
 [21 32]]


In [45]:
# Division of Two array

print(a/b)

[[0.2        0.33333333]
 [0.42857143 0.5       ]]


In [46]:
# Dot Operation of two Matrix

a.dot(b)

array([[19, 22],
       [43, 50]])