<a href="https://colab.research.google.com/github/Ar-Anik/Machine_Learning/blob/main/Numpy_Array_Operation_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import numpy

n = numpy.array([1, 2, 3, 4, 5, 6, 7, 8])

In [5]:
n[2:6]

array([3, 4, 5, 6])

In [6]:
n[-2]

7

In [8]:
n[1 : 6 : 2]

array([2, 4, 6])

In [9]:
n[ : : -1]

array([8, 7, 6, 5, 4, 3, 2, 1])

In [10]:
a = numpy.array([[1, 2, 3],
                 [4, 5, 6],
                 [7, 8, 9]
                 ])

In [12]:
a[1, 1]

5

In [13]:
a[0 : 2, 0 : 2]

array([[1, 2],
       [4, 5]])

In [14]:
a[1:2, 1]

array([5])

In [15]:
a[-1]

array([7, 8, 9])

In [16]:
a[-1, 0:2]

array([7, 8])

In [17]:
a[:, 1:3]

array([[2, 3],
       [5, 6],
       [8, 9]])

In [18]:
# Array Row and Column Print

b = numpy.array([[7, 8, 9],
                 [1, 2, 3],
                 [4, 5, 6]
                 ])

In [19]:
for row in b : 
  print(row)

[7 8 9]
[1 2 3]
[4 5 6]


In [20]:
# Print Each Cell

for cell in b.flat : 
  print(cell)

7
8
9
1
2
3
4
5
6


In [21]:
# Stack Two Array

a = numpy.arange(1, 7).reshape(3, 2)

b = numpy.arange(7, 13).reshape(3, 2)

In [22]:
a

array([[1, 2],
       [3, 4],
       [5, 6]])

In [23]:
b

array([[ 7,  8],
       [ 9, 10],
       [11, 12]])

In [24]:
# Vertically Stack Two Array

x = numpy.vstack( (a, b) )

x

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])

In [25]:
y = numpy.hstack( (a, b) )

y

array([[ 1,  2,  7,  8],
       [ 3,  4,  9, 10],
       [ 5,  6, 11, 12]])

In [28]:
# Horizontally Split Array Element

arr = numpy.arange(30).reshape(2, 15)

arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [42]:
arr_split = numpy.hsplit(arr, 3)

arr_split

[array([[ 0,  1,  2,  3,  4],
        [15, 16, 17, 18, 19]]), array([[ 5,  6,  7,  8,  9],
        [20, 21, 22, 23, 24]]), array([[10, 11, 12, 13, 14],
        [25, 26, 27, 28, 29]])]

In [33]:
arr_split[0]

array([[ 0,  1,  2,  3,  4],
       [15, 16, 17, 18, 19]])

In [34]:
arr_split[1]

array([[ 5,  6,  7,  8,  9],
       [20, 21, 22, 23, 24]])

In [37]:
arr_split[2]

array([[10, 11, 12, 13, 14],
       [25, 26, 27, 28, 29]])

In [44]:
arr_split = numpy.hsplit(arr, 4)

arr_split

ValueError: ignored

In [46]:
# Vertically Split array element

arr_split = numpy.vsplit(arr, 2)

arr_split

[array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14]]),
 array([[15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])]

In [47]:
arr_split[0]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14]])

In [48]:
arr_split[1]

array([[15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [49]:
arr_split = numpy.vsplit(arr, 3)

arr_split

ValueError: ignored

In [51]:
# Boolean Array

x = numpy.arange(1, 13).reshape(3, 4)

x

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [52]:
y = x > 5

print(y)

[[False False False False]
 [False  True  True  True]
 [ True  True  True  True]]


In [55]:
# print value of x array which element is true for y array condition

x[y]

array([ 6,  7,  8,  9, 10, 11, 12])

In [57]:
x[y] = -1

print(x)

[[ 1  2  3  4]
 [ 5 -1 -1 -1]
 [-1 -1 -1 -1]]
