<a href="https://colab.research.google.com/github/Ar-Anik/Machine_Learning/blob/main/Save_Model_Using_Joblib.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Joblib is the replacement of pickle as it is more efficient on objects that carry large numpy arrays. These functions also accept file-like object instead of filenames.

In [1]:
import pandas
import numpy
from sklearn import linear_model

In [2]:
data = pandas.read_csv('HomePrice.csv')

data

Area   Price
0  2600  550000
1  3000  565000
2  3200  610000
3  3600  680000
4  4000  725000

In [3]:
# Create Linear Regression model Object and train that model

model = linear_model.LinearRegression()
model.fit(data[['Area']], data.Price)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [6]:
# We know linear hypothesis is y = m*x + b
# here co-efficient of x is m
# b is intercept

# the value of m
model.coef_

array([135.78767123])

array([135.78767123])

In [7]:
# value of b

model.intercept_

180616.43835616432

In [8]:
# predict price of a area by linear model

model.predict([[5000]])

array([859554.79452055])

In [10]:
# save model to a file using joblib

from sklearn.externals import joblib

In [11]:
# By joblib.dump() function create a binary file where store our model

joblib.dump(model, 'joblib_file')

['joblib_file']

In [13]:
# load saved model

jb_model = joblib.load('joblib_file')

jb_model

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [15]:
# co-efficent value

jb_model.coef_

array([135.78767123])

In [16]:
# intercept value

jb_model.intercept_

180616.43835616432

In [17]:
# predict value by joblib

jb_model.predict([[5000]])

array([859554.79452055])