<a href="https://colab.research.google.com/github/Ar-Anik/Machine_Learning/blob/main/numpy_random_randn().ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [14]:
# numpy.random.randn() function creates an array and fills it with random values
# normally its take arguments like row, column etc

import numpy

numpy.random.randn()

-0.4149015658899079

In [13]:
# create 1D array

array = numpy.random.randn(5)
print(array)

[-1.52191178 -0.37499889 -0.46379821 -0.55802084  0.08735764]


In [6]:
# create 2D array

array = numpy.random.randn(5, 4)
print(array)

[[-1.13481946e-01  7.74772402e-01 -6.91646006e-01  1.47863642e+00]
 [ 6.80643807e-01 -1.54313860e-01 -5.66720816e-01 -9.40053152e-01]
 [ 5.50800483e-01 -1.08978776e+00  7.13908501e-01  2.22232273e+00]
 [ 5.29745436e-01  2.03800277e+00  3.18079462e-01  8.37899332e-01]
 [ 8.92895599e-01  6.82594118e-01  8.38985109e-04 -9.45970281e-01]]


In [7]:
# create 3D array

array = numpy.random.randn(3, 2, 4)
print(array)

[[[-0.56132476 -0.01056378  0.6218758  -0.02056568]
  [-0.58424506  0.09445029 -1.38820096  0.15811762]]

 [[-0.20086518 -0.09262912  0.09123204 -0.87769427]
  [-0.57509684  1.54606488 -0.37185644 -0.09396086]]

 [[ 0.65019898  0.14923487 -0.23643096 -1.43951505]
  [ 0.34062137 -1.02734346 -0.25725763  1.07292696]]]


In [15]:
array = numpy.random.randn(3, 2, 4)

array1 = array * 3

array2 = array * 3 + 2.5

In [16]:
print(array)

[[[ 0.53247102  1.83809591  0.45363414  0.07073341]
  [ 1.05670088 -0.57797049 -1.58913498  2.18159554]]

 [[ 1.00301327  0.12357569 -0.79032625  1.96159516]
  [-1.55206661  0.49868002 -0.66999302 -0.09174106]]

 [[ 0.34296084  0.10178049  0.52167706  0.60422558]
  [ 2.2551376   0.27779189 -0.14544278 -0.24926563]]]


In [17]:
print(array1)

[[[ 1.59741307  5.51428772  1.36090241  0.21220023]
  [ 3.17010265 -1.73391146 -4.76740495  6.54478663]]

 [[ 3.00903981  0.37072707 -2.37097876  5.88478547]
  [-4.65619984  1.49604007 -2.00997907 -0.27522318]]

 [[ 1.02888253  0.30534147  1.56503117  1.81267674]
  [ 6.76541281  0.83337567 -0.43632834 -0.74779689]]]


In [18]:
print(array2)

[[[ 4.09741307  8.01428772  3.86090241  2.71220023]
  [ 5.67010265  0.76608854 -2.26740495  9.04478663]]

 [[ 5.50903981  2.87072707  0.12902124  8.38478547]
  [-2.15619984  3.99604007  0.49002093  2.22477682]]

 [[ 3.52888253  2.80534147  4.06503117  4.31267674]
  [ 9.26541281  3.33337567  2.06367166  1.75220311]]]
