<a href="https://colab.research.google.com/github/Ar-Anik/Machine_Learning/blob/main/numpy_median().ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# numpy.median(array, axis = 0 or 1)
# Compute the median of the given array elements along the specified axis
# axis = 0 means along the column and axis = 1 means working along the row.
# [2, 3, 3, 5, 8, 10, 11] median of this array is 5
# [2, 2, 3, 3, 5, 7, 8, 130] median of this arra is, (3+5)/2=4 

In [5]:
import numpy

array = numpy.array([1, 2, 3, 4, 5])
array

array([1, 2, 3, 4, 5])

In [6]:
numpy.median(array)

3.0

In [37]:
# 2D array 

arr = numpy.array([
                     [1, 2, 3, 6],
                     [4, 5, 6, 7],
                     [7, 8, 9, 3]
])

arr

array([[1, 2, 3, 6],
       [4, 5, 6, 7],
       [7, 8, 9, 3]])

In [39]:
# array like : [1, 2, 3, 3, 4, 5, 6, 6, 7, 7, 8, 9]
# median is (5+6)/2

numpy.median(arr)

5.5

In [41]:
# 2D array median along the column

numpy.median(arr, axis = 0)

array([4., 5., 6., 6.])

In [42]:
# 2D array median along the row

numpy.median(arr, axis = 1)

array([2.5, 5.5, 7.5])